#!/usr/bin/env bash
# Create a certificate using certbot and configure HAproxy
# to accept encrypted traffic
global
        log /dev/log    local0
	stats socket /run/haproxy/admin.sock mode 660 level admin

defaults
        log     global
        mode    http
        option  httplog
	timeout connect  10s
	timeout client  30s
	timeout server  30s

frontend sikholise.tech-frontend
	bind *:80
	bind *:443 ssl crt /etc/haproxy/certs/sikholise.tech.pem
	http-request redirect scheme https unless { ssl_fc }
	http-request set-header X-Forwarded-Proto https
	default_backend sikholise.tech-backend

backend sikholise.tech-backend
	balance roundrobin
	server 413570-web-01 100.25.132.11:80 check
	server 413570-web-02 52.91.123.151:80 check
