#!/usr/bin/env bash
#  configure web-02 to be identical to web-01
apt-get  update ; apt-get -y install nginx
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
sudo service nginx restart
