#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend sikholise.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 413570-web-01 54.237.57.0
        server 413570-web-02 54.160.99.139
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
