#!/usr/bin/env bash
# This script displays to infinity and beyond indefinitely
# I am invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" 15
i=0
while [ $i -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
