#!/usr/bin/env bash
# Displays "Best School" 10 times,goodluck on 8th iteration, badluck on the 4th
i=1
while [ $i -lt 11 ]
do
	if [[ $i -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $i -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
