#!/usr/bin/env bash
# displays numbers from 1 to 20 and: bad luck from China 4th iteration
# bad luck from Japan for the 9th loop iteration
# bad luck from Italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"	
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( ++i ))
done
