#!/bin/bash env
# install the ufw firewall and setup a few rules on web-01
apt-get update
apt install ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
