#!/usr/bin/env bash
# configuration file for the local SSH client
# connect to a server without typing a password.
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
PasswordAuthentication no
IdentityFile ~/.ssh/school
