#!/usr/bin/env bash
# configuration file for the local SSH client
# connect to a server without typing a password.
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    PasswordAuthentication no
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
